# Example usage:  ansible-playbook deploy-bargainbetter-ui.yml -e 'hosts=do2'
---
  - name: deploy docker application container
    hosts: '{{hosts}}'
    tasks:
    - name: Install docker-py as needed by Ansible
      pip: name=docker-py
      become: true

    - name: pull and start mongodb container
      docker_container:
        name: mongodb
        image: mongo:latest
        restart_policy: always
        ulimits:
          mlock: -1
        capabilities:
          - IPC_LOCK
        ports:
         - "27017:27017"
        volumes:
         - /opt/docker/volumes/mongodb:/data/db