# Example usage:  ansible-playbook deploy-bargainbetter-ui.yml -e 'hosts=do2'
---
  - name: deploy docker application container
    hosts: '{{hosts}}'
    tasks:
    - name: Install docker-py as needed by Ansible
      pip: name=docker-py
      become: true

    - name: pull and start container
      docker_container:
        name: bargainbetter
        image: chrisjstevenson/bargainbetter
        state: started
        restart: yes
        restart_policy: always
        links:
         - "mongodb:mongodb"
        ports:
          - "3000:3000"   #host_port:container_port
        env:
          NODE_ENV: "{{ hostvars[inventory_hostname].environment_name }}"